# Generated by Django 2.0.1 on 2018-03-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0007_finderstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finderstatus',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
        migrations.RenameField(
            model_name='finderstatus',
            old_name='aval',
            new_name='apron',
        ),
    ]
