# Generated by Django 2.0.1 on 2018-03-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0008_auto_20180307_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finderstatus',
            name='apron',
            field=models.CharField(choices=[('Available', 'Available'), ('Nope', 'Not Available')], max_length=255),
        ),
    ]
