# Generated by Django 2.0.1 on 2018-03-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0009_auto_20180307_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='college_mate/media/post_image'),
        ),
    ]
