# Generated by Django 2.0.1 on 2018-03-15 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0011_finderstatus2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finderstatus',
            options={'verbose_name': 'Apron Status', 'verbose_name_plural': 'Apron Status'},
        ),
        migrations.AlterModelOptions(
            name='finderstatus2',
            options={'verbose_name': 'Drafter Status', 'verbose_name_plural': 'Drafter Status'},
        ),
        migrations.RemoveField(
            model_name='finderstatus2',
            name='user',
        ),
    ]
